[package]
name = "hr"
version = "0.0.2"
edition = "2021"
description = "Converts byte size into human readable format"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive", "env"] }
