name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-pull-request:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: human-readable

  publish-release:
    runs-on: ubuntu-latest
    needs: release-pull-request
    if: ${{ needs.release-pull-request.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
